### PR TITLE
feat: add support for Coinbase Wallet

### PR DESCRIPTION
**Pull request by taycaldwell**
Add support for Coinbase Wallet now that it has an [injected Solana provider](https://docs.cloud.coinbase.com/wallet-sdk/docs/solana-overview).

### CODE REVIEW

**Comment by michaelhly** [comment]
Hi @taycaldwell. Thanks for this PR! Would you mind merging in the latest master and fix the linter issue from the CI run?

**Comment by taycaldwell** [comment]
Fixed.

**Comment by michaelhly** [comment]
@taycaldwell can you run the ‘yarn’ command and then push agai?

**Comment by michaelhly** [comment]
Would you mind running `lint:fix`? 🙏

**Comment by taycaldwell** [comment]
I borked it again. 1 moment.

**Review by michaelhly — APPROVED** [review]
@taycaldwell nice! Thank you for the PR 🙏 .

**Pull request merged**
