### PR TITLE
feat: add support for walletconnect wallet

### LINKED ISSUE #699: Walletconnect support
Hi Ian, do you know if it's possible to get walletconnect support? It seems like [adapter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/wallets/walletconnect) was set up a month ago. I would be happy to create a PR but it seems that because it the adapter accepts nonstandard options such as a `projectId` field, it's slightly nontrivial to integrate (happy to take a stab). The use case I have is for fireblocks support.

### PR DESCRIPTION
**Pull request by jeffhu1**
Closes #699

### CODE REVIEW

**Comment by iulianbarbu** [comment]
@michaelhly , should we notify anyone to review this? Please let us know if we can facilitate the review with anything.

**Comment by michaelhly** [comment]
@jeffhu1 @iulianbarbu can you guys fix the build issue?
> Module not found: Error: Can't resolve 'events' in '/home/runner/.yarn/berry/cache/@walletconnect-heartbeat-npm-1.0.0-2a6f7e2ea6-8.zip/node_modules/@walletconnect/heartbeat/dist/cjs'

**Comment by jeffhu1** [comment]
I think the build issue has to do with webpack 5 in size-limit not polyfilling events

**Comment by jeffhu1** [comment]
@michaelhly The build should be fixed, works locally!

**Pull request merged**
